name: CI-linpeas_prod

on:
  pull_request:
    branches:
      - linpeas_prod

  workflow_dispatch:

jobs:
  Test_linpeas_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run linpeas
        run: linPEAS/linpeas.sh -o SysI,Container,Devs,AvaSof,ProCronSrvcsTmrsSocks,Net,UsrI,SofI
    
  Test_linpeas_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run linpeas
        run: linPEAS/linpeas.sh -a
