# This is a basic workflow to help you get started with Actions

name: CI-linpeas_dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - linpeas_dev
    paths-ignore:
      - 'linPEAS/linpeas.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build linpeas
        run: |
          python3 -m pip install PyYAML
          cd linPEAS
          python3 -m builder.linpeas_builder

      # Runs a single command using the runners shell
      - name: Run linpeas
        run: linPEAS/linpeas.sh -h

      - name: Create local changes
        run: git add linPEAS/linpeas.sh

      - name: Commit results to Github
        run: |
          git config --local user.email ""
          git config --global user.name "CI-linpeas-ubuntu"
          git commit -m "linpeas.sh auto update" -a --allow-empty
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}

      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "linpeas_prod"
          github_token: ${{ secrets.GITHUB_TOKEN }}
