name: CI-winpeas_dev_test

on:
  push:
    branches:
      - winpeas_dev
      - linpeas_dev
    paths:
      - 'build_lists/sensitive_files.yaml'
      - 'winPEAS/winPEASexe/**'

  workflow_dispatch:

jobs:

  Build_and_test_winpeas_dev:
    runs-on: windows-latest
    
    # environment variables
    env:
      Solution_Path: 'winPEAS\winPEASexe\winPEAS.sln'
      Configuration: 'Release'
      DotFuscatorGeneratedPath: 'winPEAS\winPEASexe\binaries\Obfuscated Releases\Dotfuscated'

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v2
            
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
       
      # Setup NuGet
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1  
        
      # Restore the packages for testing
      - name: Restore the application       
        run: nuget restore $env:Solution_Path
        
      # build
      - name: run MSBuild
        run: msbuild $env:Solution_Path
        
      # Execute all unit tests in the solution
      #- name: Execute unit tests
      #  run: dotnet test $env:Solution_Path
      
      
  create_pull_request:
    runs-on: ubuntu-latest
    needs: Build_and_test_winpeas_dev
    
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v2
    
      # PR     
      - name: Pull Request
        uses: repo-sync/pull-request@v2
        #uses: peter-evans/create-pull-request@v3
        #env:
        #  GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
        with:
          destination_branch: "master"
          github_token: ${{ secrets.PULL_REQUEST_TOKEN }}
          #branch: "master"
          #token: ${{ secrets.PULL_REQUEST_TOKEN }}
