name: CI-winpeas_PR

on:
  push:
    branches: 
      - winpeas_dev
    paths:
      - 'build_lists\sensitive_files.yaml'
      - 'winPEAS\winPEASexe\**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
