name: CI-winpeas_test

on:
  pull_request:
    branches:
      - winpeas_dev
    paths:
      - 'build_lists\sensitive_files.yaml'
      - 'winPEAS\winPEASexe\**'

  workflow_dispatch:

jobs:  

  Build_and_test_winpeas:
    runs-on: windows-latest
    
    # environment variables
    env:
      Solution_Path: 'winPEAS\winPEASexe\winPEAS.sln'      
      Configuration: 'Release'

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v2
         
      # Install the .NET
      - name: Install .NET 4.5.2
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.5.2'
            
      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      # Restore the packages for testing
      - name: Restore the application
        run: msbuild -m $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration        
        
      # build
      - name: run MSBuild
        run: msbuild $env:Solution_Path
        
      # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test $env:Solution_Path
